Add support for additional services
MozillaSecurity/grizzly pull request #365
Opened 2023-05-15 15:31 UTC by pyoor

Add's support for running additional services during fuzzing, replay, and reduction.  This PR also adds a basic WebTransport service.

2023-05-16 18:29 UTC, tysmith requested changes

2023-05-16 18:29 UTC, tysmith commented on grizzly_services/webtransport/test_webtransport.py
> +        assert web_transport._started is False
Blanket `is False` replace with `not` and remove `is True`.

2023-05-16 19:39 UTC, jschwartzentruber requested changes

2023-05-16 19:39 UTC, jschwartzentruber commented on grizzly/replay/replay.py
> +                        create_cb(b"https://127.0.0.1:%d" % (service.port,)),
I think one of Tyson's comments got eaten regarding the lambdas.... This is wrong. Either create the function to return a bytestring and pass that, or use a lambda and ignore the pylint warning.

```python

def create_url():
    return f"https://127.0.0.1:{service.port}".encode("ascii")

server_map.set_dynamic_response("grz_webtransport_server", create_url, ...)
```

2023-05-16 19:39 UTC, jschwartzentruber commented on grizzly_services/core.py
> +        self.services = services
and use an enum for the service type (dict key) rather than just a string.

2023-05-16 19:39 UTC, jschwartzentruber commented on grizzly_services/webtransport/__main__.py
> +import argparse
this file doesn't look like it was meant to be included.

2023-05-16 19:39 UTC, jschwartzentruber commented on setup.cfg
> +    aioquic >= 0.9.20
Should this be `~= 0.9.20` ? I notice wst uses `==`

2025-02-19 21:05 UTC, pyoor commented on grizzly_services/webtransport/core.py
> +        for _ in range(3):
This was resolved with async/await.

2025-02-24 20:24 UTC, closed without merging

2025-02-24 20:24 UTC, pyoor commented
Due to the long timeline here and force pushes, I'm going to close this and open a new one.